# Generated by Django 3.1 on 2020-08-25 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_joobcatagery'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('salaryminm', models.IntegerField()),
                ('salarymaxm', models.IntegerField()),
                ('tags', models.CharField(max_length=200)),
                ('job_description', models.TextField(max_length=200)),
                ('upload_documents', models.FileField(upload_to='jobfiles/')),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_user', to=settings.AUTH_USER_MODEL)),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcatagery', to='jobs.joobcatagery')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addjob', to='jobs.jobstypes')),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
