# Generated by Django 3.1 on 2020-08-25 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0003_addjobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyNow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('contact_number', models.EmailField(max_length=200)),
                ('upload_doc', models.FileField(upload_to='jobfiles/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('addjob_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcategory', to='jobs.addjobs')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
