# Generated by Django 2.2.8 on 2020-08-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='add_files',
            field=models.FileField(blank=True, null=True, upload_to='rnd_proje/'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='proposal',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='bid_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
