# Generated by Django 2.2.8 on 2020-06-22 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rnd_projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('description', models.CharField(max_length=10000)),
                ('technology', models.CharField(max_length=1000)),
                ('skill', models.CharField(max_length=1000)),
                ('screenshort', models.FileField(upload_to='proje/')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createquestionsuser', to=settings.AUTH_USER_MODEL)),
                ('updated_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updatquestionsuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
