# Generated by Django 2.2.8 on 2020-08-07 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rnd_projects', '0002_auto_20200807_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikePlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_plan_name', models.CharField(max_length=100)),
                ('like_description', models.TextField(max_length=2000)),
                ('like_price', models.IntegerField()),
                ('like', models.IntegerField()),
                ('like_features1', models.CharField(max_length=500)),
                ('like_features2', models.CharField(max_length=500)),
                ('like_othersfeatures3', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Paytm_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDERID', models.CharField(max_length=30, verbose_name='ORDER ID')),
                ('TXNDATE', models.DateTimeField(default=django.utils.timezone.now, verbose_name='TXN DATE')),
                ('TXNID', models.CharField(max_length=100, verbose_name='TXN ID')),
                ('BANKTXNID', models.CharField(blank=True, max_length=100, null=True, verbose_name='BANK TXN ID')),
                ('BANKNAME', models.CharField(blank=True, max_length=50, null=True, verbose_name='BANK NAME')),
                ('RESPCODE', models.IntegerField(verbose_name='RESP CODE')),
                ('PAYMENTMODE', models.CharField(blank=True, max_length=10, null=True, verbose_name='PAYMENT MODE')),
                ('CURRENCY', models.CharField(blank=True, max_length=4, null=True, verbose_name='CURRENCY')),
                ('GATEWAYNAME', models.CharField(blank=True, max_length=30, null=True, verbose_name='GATEWAY NAME')),
                ('MID', models.CharField(max_length=40)),
                ('RESPMSG', models.TextField(max_length=250, verbose_name='RESP MSG')),
                ('TXNAMOUNT', models.FloatField(verbose_name='TXN AMOUNT')),
                ('PLANPRICE', models.FloatField()),
                ('GST', models.FloatField()),
                ('STATUS', models.CharField(max_length=12, verbose_name='STATUS')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_payment_paytm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcceptBiddata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biddingid', models.IntegerField()),
                ('status', models.CharField(default=0, max_length=300)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('bid_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_userid', to=settings.AUTH_USER_MODEL)),
                ('task_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_userid', to=settings.AUTH_USER_MODEL)),
                ('taskid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_id_id', to='rnd_projects.AddPostdatas')),
            ],
        ),
    ]
