# Generated by Django 2.2.8 on 2020-06-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd_projects', '0002_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='technology',
            field=models.CharField(choices=[('Code Error', 'Code Error'), ('Task Guide', 'Task Guide'), ('Technology', 'Technology'), ('Database', 'Database')], max_length=10),
        ),
    ]
