# Generated by Django 2.2.8 on 2020-06-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd_projects', '0003_auto_20200623_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='technology',
            field=models.CharField(max_length=1000),
        ),
    ]
