# Generated by Django 3.1 on 2020-08-24 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rnd_projects', '0003_acceptbiddata_likeplans_paytm_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ci', to=settings.AUTH_USER_MODEL)),
                ('taskid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tsk', to='rnd_projects.addpostdatas')),
                ('updated_user', models.OneToOneField(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='us', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciii', to=settings.AUTH_USER_MODEL)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quii', to='rnd_projects.questions')),
                ('updated_user', models.OneToOneField(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='usfff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
