# Generated by Django 2.2.8 on 2020-06-23 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rnd_projects', '0004_auto_20200623_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createuserid', to=settings.AUTH_USER_MODEL)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createquestionsid', to=settings.AUTH_USER_MODEL)),
                ('question_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createquestionsuserid', to='rnd_projects.Questions')),
                ('updated_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updateuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
