# Generated by Django 2.2.8 on 2020-06-25 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rnd_projects', '0005_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='updated_user',
            field=models.OneToOneField(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='updateuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
