# Generated by Django 2.2.8 on 2020-06-28 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rnd_projects', '0005_answer_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPostdatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('Category', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
                ('your_estimated_budget_minimum', models.CharField(max_length=200)),
                ('your_estimated_budget_maximum', models.CharField(max_length=200)),
                ('skills_are_required', models.CharField(max_length=200)),
                ('Describe_Your_Post', models.TextField(max_length=20000)),
                ('upload_file', models.FileField(upload_to='proje/')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdaddostsuser', to=settings.AUTH_USER_MODEL)),
                ('updated_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updataddpostuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BidCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_bid', models.IntegerField()),
                ('user_id', models.IntegerField(unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=2000)),
                ('price', models.IntegerField()),
                ('bid', models.IntegerField()),
                ('features1', models.CharField(max_length=500)),
                ('features2', models.CharField(max_length=500)),
                ('othersfeatures3', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.IntegerField()),
                ('create_bid_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('bid_type', models.CharField(max_length=200)),
                ('delivery_time', models.IntegerField()),
                ('update_time', models.DateTimeField(null=True)),
                ('bid_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biduser', to=settings.AUTH_USER_MODEL)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_task_id', to='rnd_projects.AddPostdatas')),
            ],
        ),
    ]
