# Generated by Django 2.2.8 on 2020-06-29 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rnd_projects', '0006_addpostdatas_bidcount_bidding_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replyreply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replyreply', models.CharField(max_length=500000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answerssssssssid', to='rnd_projects.Answer')),
                ('created_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdddddduser', to=settings.AUTH_USER_MODEL)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createquestionssssid', to='rnd_projects.Questions')),
                ('reply_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replyyyyyssssid', to='rnd_projects.Reply')),
                ('updated_user', models.OneToOneField(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='updateeddddduser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
