# Generated by Django 2.2.8 on 2020-07-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnd_projects', '0007_order_paymentdetails_projectorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects_add_documents',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='proje/'),
        ),
    ]
