# Generated by Django 2.2.8 on 2020-07-27 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rnd_projects', '0008_projects_add_documents_zip_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=15, max_digits=30)),
                ('t_p_q_id', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cu', to=settings.AUTH_USER_MODEL)),
                ('updated_user', models.OneToOneField(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='ur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
